### ISSUE TITLE
Unix time not working in Alfred 3

### ISSUE THREAD

**Issue by andybergon** [mwaterfall/alfred-datetime-format-converter#12]
The conversion from unix time is not working for me. 

I am using Alfred 3 but this should not matter as putting `now` works as expected.

![image](https://user-images.githubusercontent.com/5220825/32500148-6b5c4d1c-c3cc-11e7-8b9b-1351a6847c7f.png)

![image](https://user-images.githubusercontent.com/5220825/32500133-62baa0d2-c3cc-11e7-89f4-b3a12530e738.png)

**Comment by cfurrow** [comment]
Must not support timestamps that are greater than 12 digits.

`df 151006564978` works
`df 1510065649788` does not

**Comment by andybergon** [comment]
My bad. I don't know why I thought the extension was about milliseconds and not seconds :)
